### ISSUE TITLE
Collaborating on another flask-casbin implementation?

### ISSUE THREAD

**Issue by dfresh613** [daymien/Flask-Casbin#1]
We have recently opensourced the repository: https://github.com/ScienceLogic/flask-casbin as well as a few other casbin related repositories.
 
It seems like you are working to solve the same problem with this codebase. Would you be interested in collaborating on our existing project, rather than continuing with this new one? We have already implemented enforcer decorators, and the ability to load casbin models via config file. If so, I'd like to explore the possibility of using the current `flask-casbin` module which is available on pypi.
 
If you are not interested in collaborating, that's just fine! We can find a new name for our .whl to upload to pypi :)
 
Thanks

**Comment by wyhimself** [comment]
My first time to find a new .whl in first version. Nice to see that you all want to do this. if something happend, plz tell me!glad to c

**Comment by hsluoyz** [comment]
Why don't develop on the official flask authz middleware: https://github.com/pycasbin/flask-authz ?

**Comment by dfresh613** [comment]
@hsluoyz  The first line of that repository readme says: `This repo is just a working Flask app that shows the usage of flask-authz`

Per the readme, it seems that repo was more of just a reference example of how casbin can be used with flask, but did not provide any real tooling or framework which can be re-used in a generic way to enable any flask app to utilize casbin decorators, and user defined models.

**Comment by hsluoyz** [comment]
@dfresh613 well, I'm not a Python expert. So I don't know how to write a general middleware. It seems that I have written it into an example. But I always want it to be a general middleware. Can you help on it via PR?

**Comment by dfresh613** [comment]
@hsluoyz  Thanks for the information, we'd be happy to merge our code into your repo. We will open a PR

**Comment by reimundklain** [comment]
@dfresh613 @hsluoyz I just realized there is a official version of this project/idea. I don't really have time to work or maintain this project as you see in my history. Therefore if you like I could make free the pypi name for the official version and you could change name.
