### ISSUE TITLE
Version of casbin

### ISSUE THREAD

**Issue by cjauvin** [daymien/Flask-Casbin#2]
Hi, I'm new to casbin, flask-casbin and pyproject.toml. When I pip install flask-casbin in a new venv (with pip 21.1) the version of casbin that gets installed seems quite old: 0.8.4. When I try to upgrade it I get this error:

```
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
flask-casbin 0.2.1 requires casbin<0.9.0,>=0.8.1, but you have casbin 1.1.2 which is incompatible.
```

I cannot find the place in the flask-casbin repo where this requirement is specified.

**Comment by hsluoyz** [comment]
See:

https://github.com/daymien/Flask-Casbin/blob/39f720b7e3cca1395a5b06619ab38972def35111/poetry.lock#L24-L30

@cjauvin can you make a PR to update the version in dependency?
